### PR TITLE
NFT rewards

### LINKED ISSUE #3: Broken Permit Format
- https://github.com/ubiquity/pay.ubq.fi/pull/146 appears to have changed the format that it expects the permits to be encoded in. 
- Example: https://github.com/ubiquity/work.ubq.fi/issues/1#issuecomment-1910279707
   - > "ERROR | INVALID CLAIM DATA PASSED IN URL"

Please match the permit encoding format in this codebase.

### PR DESCRIPTION
**Pull request by whilefoo**
Resolves #3

### CODE REVIEW

**Comment by whilefoo** [comment]
finally managed to do it

**Comment by pavlovcik** [comment]
Glad to see you figured it out. I'll try and review on my computer in a few hours.

File: src/handlers/issue/generate-nft-mint-signature.ts [hunk 1]
```diff
@@ -0,0 +1,127 @@
+import { BigNumber, BigNumberish, ethers, utils } from "ethers";
+import { getPayoutConfigByNetworkId } from "../../helpers/payout";
+import { MaxUint256 } from "@uniswap/permit2-sdk";
+import { keccak256, toUtf8Bytes } from "ethers/lib/utils";
+
+const NFT_MINTER_PRIVATE_KEY = process.env.NFT_MINTER_PRIVATE_KEY as string;
+const NFT_CONTRACT_ADDRESS = process.env.NFT_CONTRACT_ADDRESS as string;
+const NFT_CONTRACT_CHAIN_ID = parseInt(process.env.NFT_CONTRACT_CHAIN_ID as string);
```
Comment (pavlovcik) [inline src/handlers/issue/generate-nft-mint-signature.ts:8]: I think we should not rely on environment variables. Instead these should be read from the config yml.

File: src/handlers/issue/generate-nft-mint-signature.ts [hunk 2]
```diff
@@ -0,0 +1,127 @@
...
+const SIGNING_DOMAIN_NAME = "NftReward-Domain";
```
Comment (pavlovcik) [inline src/handlers/issue/generate-nft-mint-signature.ts:9]: Should we use a more deliberate string? Why did you choose this?

File: src/handlers/issue/generate-nft-mint-signature.ts [hunk 3]
```diff
@@ -0,0 +1,127 @@
...
+const SIGNING_DOMAIN_VERSION = "1";
```
Comment (pavlovcik) [inline src/handlers/issue/generate-nft-mint-signature.ts:10]: What is this for?

File: src/handlers/issue/generate-nft-mint-signature.ts [hunk 4]
```diff
@@ -0,0 +1,127 @@
...
+
+interface NftMintRequest {
+  beneficiary: string;
+  deadline: BigNumberish;
```
Comment (pavlovcik) [inline src/handlers/issue/generate-nft-mint-signature.ts:14]: Shouldn't we use `BigNumber` instead? That seems more type safe.

File: src/handlers/issue/generate-nft-mint-signature.ts [hunk 5]
```diff
@@ -0,0 +1,127 @@
...
+    adminWallet = new ethers.Wallet(NFT_MINTER_PRIVATE_KEY, provider);
+  } catch (error) {
+    throw console.error("Failed to instantiate wallet", error);
+  }
+
+  const nftMintRequest: NftMintRequest = {
+    beneficiary: beneficiary,
+    deadline: MaxUint256,
+    keys: keys.map((key) => utils.keccak256(utils.toUtf8Bytes(key))),
+    nonce: BigNumber.from(keccak256(toUtf8Bytes(`${organizationName}${repositoryName}${issueNumber}${username}`))),
```
Comment (pavlovcik) [inline src/handlers/issue/generate-nft-mint-signature.ts:96]: I vaguely recall that we have the values delimitated with hyphens. This won't affect runtime behavior in any way but code consistency is nice. Let's be sure to match styles if there is any differentiation. 

```suggestion
    nonce: BigNumber.from(keccak256(toUtf8Bytes(`${organizationName}-${repositoryName}-${issueNumber}-${username}`))),
```

File: src/handlers/issue/generate-permit-2-signature.ts [hunk 6]
```diff
@@ -47,7 +50,7 @@ export async function generatePermit2Signature({
       amount: ethers.utils.parseUnits(amount.toString(), 18),
     },
     spender: beneficiary,
-    nonce: BigNumber.from(keccak256(toUtf8Bytes(userId))),
+    nonce: BigNumber.from(keccak256(toUtf8Bytes(`${organizationName}${repositoryName}${issueNumber}${userId}`))),
```
Comment (pavlovcik) [inline src/handlers/issue/generate-permit-2-signature.ts:53]: Delimitation. 

```suggestion
    nonce: BigNumber.from(keccak256(toUtf8Bytes(`${organizationName}-${repositoryName}-${issueNumber}-${userId}`))),
```

File: src/handlers/issue/generate-permits.ts [hunk 7]
```diff
@@ -47,17 +51,44 @@ async function generateComment(totals: TotalsById, issue: GitHubIssue, config: B
...
+        username: contributorName,
+        contributionType: contributions,
+      });
+      nftMints.push(nftMint);
+      allTxs.push(nftMint);
+    }
+
+    const claimData = [
+      ...permits.map((permit) => ({ type: "permit", ...permit })),
+      ...nftMints.map((nftMint) => ({ type: "nft-mint", ...nftMint })),
```
Comment (pavlovcik) [inline src/handlers/issue/generate-permits.ts:84]: Perhaps it makes sense to be more deliberate with the variable naming. For example, both are permits. One is for fungible tokens, and the other for NFTs. Examples:

- `erc20CompliantPermit`
- `erc721CompliantPermit`

Or

- `nonFungiblePermit`
- `fungiblePermit`

**Review by pavlovcik — CHANGES_REQUESTED** [review]
The only change that makes me refuse merging this is that we should not be relying on secrets/environment variables for configuration. It should always be handled in the `ubiquibot-config.yml` unless the value actually needs to be secret (i.e. Open AI API key.)

The other problems I note can be handled in hotfix pull requests.

File: src/handlers/issue/generate-nft-mint-signature.ts (hunk 2 above)
Comment (whilefoo) [reply src/handlers/issue/generate-nft-mint-signature.ts:9]: this was hardcoded when the [contract](https://github.com/ubiquity/nft-rewards) was deployed

File: src/handlers/issue/generate-nft-mint-signature.ts (hunk 3 above)
Comment (whilefoo) [reply src/handlers/issue/generate-nft-mint-signature.ts:10]: this is used for signing the NFT mint request

File: src/handlers/issue/generate-nft-mint-signature.ts (hunk 4 above)
Comment (whilefoo) [reply src/handlers/issue/generate-nft-mint-signature.ts:14]: `BigNumberish` accepts either a number or `BigNumber`. If the deadline is a Unix timestamp it will fit into number type and you can just use new Date().getMilliseconds()

File: src/handlers/issue/generate-permits.ts (hunk 7 above)
Comment (whilefoo) [reply src/handlers/issue/generate-permits.ts:84]: makes sense!

File: src/handlers/issue/generate-nft-mint-signature.ts (hunk 1 above)
Comment (whilefoo) [reply src/handlers/issue/generate-nft-mint-signature.ts:8]: This is a contract we deploy and not something partners should change so I don't think it makes sense to put it in the config.

File: src/handlers/issue/generate-nft-mint-signature.ts (hunk 3 above)
Comment (pavlovcik) [reply src/handlers/issue/generate-nft-mint-signature.ts:10]: `SIGNING_DOMAIN_VERSION`

File: src/handlers/issue/generate-nft-mint-signature.ts (hunk 1 above)
Comment (pavlovcik) [reply src/handlers/issue/generate-nft-mint-signature.ts:8]: Perhaps we should hard code it then and be sure to use `CREATE2` to specify the same deploy address on all networks that Permit2 is deployed on? @rndquu

Comment (rndquu) [reply src/handlers/issue/generate-nft-mint-signature.ts:8]: > This is a contract we deploy and not something partners should change so I don't think it makes sense to put it in the config.

Yes, we can either hardcode it either use env variables. I would use env variables right now and when https://github.com/ubiquity/nft-rewards/issues/2 is ready we could hardcode the address.

File: src/handlers/issue/generate-nft-mint-signature.ts (hunk 2 above)
Comment (pavlovcik) [reply src/handlers/issue/generate-nft-mint-signature.ts:9]: Seems odd to me that we have to pass this in as a parameter. @rndquu rfc

File: src/handlers/issue/generate-nft-mint-signature.ts (hunk 3 above)
Comment (pavlovcik) [reply src/handlers/issue/generate-nft-mint-signature.ts:10]: Seems odd to me that we have to pass this in as a parameter. @rndquu rfc

File: src/handlers/issue/generate-nft-mint-signature.ts (hunk 4 above)
Comment (pavlovcik) [reply src/handlers/issue/generate-nft-mint-signature.ts:14]: I think it makes more sense to only support a single type of input. Unix timestamp seems to make the most sense. Let's use `number` type instead?

File: src/handlers/issue/generate-nft-mint-signature.ts (hunk 5 above)
Comment (pavlovcik) [reply src/handlers/issue/generate-nft-mint-signature.ts:96]: Hey @whilefoo it looks like we are only using the user id which doesn't seem right to me. I thought that we at least encode the issue ID? 

https://github.com/ubiquibot/comment-incentives/blob/7b88ed93321d902cf6e7f41cc839ccf105dedbdf/src/handlers/issue/generate-permit-2-signature.ts#L50

@wannacfuture rfc

File: src/handlers/issue/generate-nft-mint-signature.ts (hunk 1 above)
Comment (pavlovcik) [reply src/handlers/issue/generate-nft-mint-signature.ts:8]: @whilefoo please hard code. I just made a note about this in https://github.com/ubiquity/nft-rewards/issues/2.

File: src/handlers/issue/generate-nft-mint-signature.ts (hunk 2 above)
Comment (whilefoo) [reply src/handlers/issue/generate-nft-mint-signature.ts:9]: it's part of [EIP712](https://eips.ethereum.org/EIPS/eip-712) spec

File: src/handlers/issue/generate-nft-mint-signature.ts (hunk 1 above)
Comment (whilefoo) [reply src/handlers/issue/generate-nft-mint-signature.ts:8]: But if hardcode the private key anyone who can see the code can see the private key

File: src/handlers/issue/generate-nft-mint-signature.ts (hunk 4 above)
Comment (whilefoo) [reply src/handlers/issue/generate-nft-mint-signature.ts:14]: if we want permit to never expire we use BigNumber.MaxUint256, so if you want to narrow the type it's better to choose BigNumber

File: src/handlers/issue/generate-nft-mint-signature.ts (hunk 1 above)
Comment (pavlovcik) [reply src/handlers/issue/generate-nft-mint-signature.ts:8]: I am really confused. It doesn't help that I'm on my phone now and can't conveniently review the code in its entirety but why would a smart contract have a private key associated? Can you explain with full context?

File: src/handlers/issue/generate-nft-mint-signature.ts (hunk 2 above)
Comment (pavlovcik) [reply src/handlers/issue/generate-nft-mint-signature.ts]: > Protocol designers only need to include the fields that make sense for their signing domain. Unused fields are left out of the struct type.

File: src/handlers/issue/generate-nft-mint-signature.ts (hunk 3 above)
Comment (pavlovcik) [reply src/handlers/issue/generate-nft-mint-signature.ts]: > User
is `string version` mandatory to pass in as a param

> ChatGPT
Yes, in the context of EIP-712, the string version parameter is mandatory. This is because EIP-712 specifies a structured data hashing and signing mechanism that relies on a versioning system. The version parameter, typically a string, helps in identifying the specific version of the EIP-712 standard being used. This is important for ensuring compatibility and understanding the structure of the data being signed, as different versions might have slight variations in their implementation.

File: src/handlers/issue/generate-erc721-permit-signature.ts [hunk 8]
```diff
@@ -1,27 +1,27 @@
...
+import { BigNumber, ethers, utils } from "ethers";
 import { getPayoutConfigByNetworkId } from "../../helpers/payout";
 import { MaxUint256 } from "@uniswap/permit2-sdk";
 import { keccak256, toUtf8Bytes } from "ethers/lib/utils";
 
 const NFT_MINTER_PRIVATE_KEY = process.env.NFT_MINTER_PRIVATE_KEY as string;
-const NFT_CONTRACT_ADDRESS = process.env.NFT_CONTRACT_ADDRESS as string;
-const NFT_CONTRACT_CHAIN_ID = parseInt(process.env.NFT_CONTRACT_CHAIN_ID as string);
+const NFT_CONTRACT_ADDRESS = "0x6a87f05a74AB2EC25D1Eea0a3Cd24C3A2eCfF3E0";
+const NFT_CONTRACT_NETWORK_ID = 100;
```
Comment (pavlovcik) [inline src/handlers/issue/generate-erc721-permit-signature.ts:8]: I think we should deploy on all the networks that `permit2` is on and then take this value from the config since we already have it there! For now, @whilefoo, please take it from the existing value in the config.

File: src/handlers/issue/generate-erc721-permit-signature.ts [hunk 9]
```diff
@@ -89,39 +91,39 @@ export async function generateNftMintSignature({
...
+      values: erc721SignatureData.values,
     },
     nftMetadata,
     nftAddress: NFT_CONTRACT_ADDRESS,
     networkId: NFT_CONTRACT_CHAIN_ID,
     signature: signature,
   };
 
-  console.info("Generated nft mint signature", { transactionData });
+  console.info("Generated ERC721 permit signature", { erc721Data });
```
Comment (pavlovcik) [inline src/handlers/issue/generate-erc721-permit-signature.ts:126]: Don't you think its more semantically correct to say "Generated ERC721 compliant permit signature"

File: src/handlers/issue/generate-permits.ts [hunk 10]
```diff
@@ -51,37 +52,35 @@ async function generateComment(totals: TotalsById, issue: GitHubIssue, config: B
 
     const beneficiaryAddress = data.length > 0 ? data[0].wallets.address : "";
 
-    const permits = [];
-    const permit = await generatePermit2Signature({
+    const erc20Permits = [];
```
Comment (pavlovcik) [inline src/handlers/issue/generate-permits.ts:55]: I think it makes sense to make the variable names shorthand like this `erc20Permits` instead of `erc20CompliantPermits` probably.

File: src/handlers/issue/generate-nft-mint-signature.ts (hunk 1 above)
Comment (whilefoo) [reply src/handlers/issue/generate-nft-mint-signature.ts]: When you deploy the NFT contract you specify a minter's address. You need that minter's private key to sign mint requests. A bounty hunter can mint an NFT using that signature and pays the gas fee instead of us.

It's similar to Permit2 but in that case, the partner's wallet has the tokens so they specify their wallet's private key in `evmPrivateKeyEncrypted` field in the config.

File: src/handlers/issue/generate-nft-mint-signature.ts (hunk 3 above)
Comment (whilefoo) [reply src/handlers/issue/generate-nft-mint-signature.ts]: I'm pretty sure if we change any of the fields or skip them, the hash will be different and NFT mint will fail, but @rndquu can tell for sure

File: src/handlers/issue/generate-nft-mint-signature.ts (hunk 2 above)
Comment (rndquu) [reply src/handlers/issue/generate-nft-mint-signature.ts]: Setting `SIGNING_DOMAIN_NAME` (i.e. contract domain name) and contract version are [required](https://github.com/OpenZeppelin/openzeppelin-contracts/blob/61117c4db8497ba489d5e1e127565a011ed6907a/contracts/utils/cryptography/EIP712.sol#L66) by openzeppelin's implementation of [EIP-712](https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/contracts/utils/cryptography/EIP712.sol)

File: src/handlers/issue/generate-nft-mint-signature.ts (hunk 3 above)
Comment (rndquu) [reply src/handlers/issue/generate-nft-mint-signature.ts]: > I'm pretty sure if we change any of the fields or skip them, the hash will be different and NFT mint will fail, but @rndquu can tell for sure

Exactly, contract version is required, pls check [this](https://github.com/ubiquibot/comment-incentives/pull/4#discussion_r1470136916) comment

**Review by pavlovcik — APPROVED** [review]
